### ISSUE TITLE
Whitespace in otherwise empty fields causes import to fail

### ISSUE THREAD

**Issue by chriszs** [PublicI/fec-loader#27]
```
error inserting 904534:
    { error: invalid input syntax for type date: "  "
```

**Comment by chriszs** [comment]
Possibly related:
```
{ SequelizeDatabaseError: invalid input syntax for integer: "	"
    at Query.formatError (/home/sysadmin/fec-loader/node_modules/fec-model/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)
    at .<anonymous> (/home/sysadmin/fec-loader/node_modules/fec-model/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
    at emitOne (events.js:96:13)
--
     constraint: undefined,
     file: 'numutils.c',
     line: '62',
     routine: 'pg_atoi',
     sql: 'INSERT INTO "fec_filings" ("filing_id","record_type","ef_type","fec_version","soft_name","soft_ver","report_id","report_number","created_date","updated_date") VALUES (\'1101352\',\'HDR\',\'FEC\',\'8.1\',\'FECfile\',\'8.1.0.4(f30)\',NULL,\'\t\',\'2016-10-14 19:15:09.075 +00:00\',\'2016-10-14 19:15:09.075 +00:00\');' },
```
